---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Log
- type: directory
  path: src/content/books
  label: Books
  create: all
  match: "**/*"
  exclude: "*.json"
  templates:
  - book
- type: directory
  path: src/content/movies
  label: Movies
  create: all
  match: "**/*"
  exclude: "*.json"
  templates:
  - movie
- type: directory
  path: src/content/shows
  label: Shows
  create: all
  match: "**/*"
  exclude: "*.json"
  templates:
  - tv-show
- type: heading
  label: Pages
- type: document
  path: src/content/about/index.md
  label: About
- type: document
  path: src/content/stats/index.md
  label: Stats
- type: document
  path: src/content/404.md
  label: '404'
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
